### ISSUE TITLE
identity, prelu support

### ISSUE THREAD

**Issue by yunhaia** [JDAI-CV/DNNLibrary#13]
Do you have any plan to support full ONNX OP, like Identify,  PRelu OP.  @daquexian

**Comment by daquexian** [comment]
Thanks for your interest in DNNLibrary!

New op support is always helpful and welcome. If some unsupported OPs block
your work, please let me know what exactly the OPs are and I'll manage to
support them.

And please feel free to submit a PR if you have implemented some OPs
unsupported by me.

Thanks!

**Comment by yunhaia** [comment]
Thanks, I upload the ONNX model to BaiduPan. you can check with it. 
1. https://pan.baidu.com/s/1zyJMdrIkXO6E46NzGlqgYA

Two OP does not support when using onnx2daq
1) Identify
2) PRelu

by the way , I viewed the ONNX model with this page https://lutzroeder.github.io/netron/

**Comment by daquexian** [comment]
In version 0.6.0 identity and prelu should be supported (please also use the latest onnx2daq)

**Comment by daquexian** [comment]
I will close this issue since prelu and identity has been supported. More onnx operators support will be tracked in #17
