### ISSUE TITLE
Protobuf compiler not found

### ISSUE THREAD

**Issue by smilexin** [JDAI-CV/DNNLibrary#28]
After cloned the master repository, I followed the guide,  mkdir build, cd build and do the command "cmake .." , then the following error occured, can someone make it out what's happend? How to fix it? thanks~

-- Performing Test HAVE_RWLOCK - Success
-- Performing Test HAVE___DECLSPEC
-- Performing Test HAVE___DECLSPEC - Failed
-- Performing Test STL_NO_NAMESPACE
-- Performing Test STL_NO_NAMESPACE - Failed
-- Performing Test STL_STD_NAMESPACE
-- Performing Test STL_STD_NAMESPACE - Success
-- Performing Test HAVE_USING_OPERATOR
-- Performing Test HAVE_USING_OPERATOR - Success
-- Performing Test HAVE_NAMESPACES
-- Performing Test HAVE_NAMESPACES - Success
-- Performing Test HAVE_GCC_TLS
-- Performing Test HAVE_GCC_TLS - Success
-- Performing Test HAVE_MSVC_TLS
-- Performing Test HAVE_MSVC_TLS - Failed
-- Performing Test HAVE_CXX11_TLS
-- Performing Test HAVE_CXX11_TLS - Failed
-- Performing Test HAVE_LOCALTIME_R
-- Performing Test HAVE_LOCALTIME_R - Success
-- Configuring onnx...
-- Build type not set - defaulting to Release
CMake Error at third_party/onnx/CMakeLists.txt:218 (message):
  Protobuf compiler not found
Call Stack (most recent call first):
  third_party/onnx/CMakeLists.txt:249 (relative_protobuf_generate_cpp)

-- Configuring incomplete, errors occurred!

**Comment by daquexian** [comment]
Hi :) Thanks for using dnnlibrary.

You need to install protobuf :) You can find how to install it on your operation system via google, for ubuntu [this gist](https://gist.github.com/rvegas/e312cb81bbb0b22285bc6238216b709b) may work.

**Comment by smilexin** [comment]
Thanks so much :)  That it is~.  And I refer the following to install protobuf: https://github.com/protocolbuffers/protobuf/blob/master/src/README.md

**Comment by daquexian** [comment]
@smilexin Glad to see it :)

**Comment by daquexian** [comment]
Since 1cfd5e7, the protobuf source code in third_party is used, no more need to install protobuf manually :)
