### ISSUE TITLE
Failed to build the project

### ISSUE THREAD

**Issue by bin913** [JDAI-CV/DNNLibrary#4]
# The project was build in Android studio 3.0, and sdk had been updated.
## (1) Gradle build report following errors:

Information:Gradle tasks [:openCVLibrary320:generateDebugSources, :openCVLibrary320:generateDebugAndroidTestSources, :openCVLibrary320:mockableAndroidJar, :openCVLibrary320:compileDebugAndroidTestSources, :openCVLibrary320:compileDebugUnitTestSources, :openCVLibrary320:compileDebugSources, :dnnlibrary:generateDebugSources, :dnnlibrary:generateDebugAndroidTestSources, :dnnlibrary:mockableAndroidJar, :dnnlibrary:compileDebugAndroidTestSources, :dnnlibrary:compileDebugUnitTestSources, :dnnlibrary:compileDebugSources, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources, :app:compileDebugSources]
/home/bzhang/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake
Error:(409)  CMAKE_CXX_COMPILER not set, after EnableLanguage 
Error:(409)  CMAKE_CXX_COMPILER not set, after EnableLanguage 
Error:(409)  CMAKE_CXX_COMPILER not set, after EnableLanguage 
Error:(409)  CMAKE_CXX_COMPILER not set, after EnableLanguage 
Error:(409)  CMAKE_CXX_COMPILER not set, after EnableLanguage 
Error:(409)  CMAKE_CXX_COMPILER not set, after EnableLanguage 
Error:(409)  CMAKE_CXX_COMPILER not set, after EnableLanguage 
Error:A problem occurred configuring project ':dnnlibrary'.
> executing external native build for cmake /home/username/work/Git/DNNLibrary/dnnlibrary/CMakeLists.txt
Information:BUILD FAILED in 0s
Information:8 errors
Information:0 warnings
Information:See complete output in console
## (2) Gradle Sync report following errors
Build command failed.
Error while executing process /home/username/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/home/username/work/Git/DNNLibrary/dnnlibrary -B/home/bzhang/work/Git/DNNLibrary/dnnlibrary/.externalNativeBuild/cmake/release/armeabi -DANDROID_ABI=armeabi -DANDROID_PLATFORM=android-26 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/username/work/Git/DNNLibrary/dnnlibrary/build/intermediates/cmake/release/obj/armeabi -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/home/username/Android/Sdk/ndk-bundle -DCMAKE_CXX_FLAGS=-frtti -fexceptions -std=c++11 -DCMAKE_TOOLCHAIN_FILE=/home/username/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/username/Android/Sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_PLATFORM=android-27}
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Build command failed.
Error while executing process /home/username/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/home/username/work/Git/DNNLibrary/dnnlibrary -B/home/bzhang/work/Git/DNNLibrary/dnnlibrary/.externalNativeBuild/cmake/debug/armeabi -DANDROID_ABI=armeabi -DANDROID_PLATFORM=android-26 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/username/work/Git/DNNLibrary/dnnlibrary/build/intermediates/cmake/debug/obj/armeabi -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/home/username/Android/Sdk/ndk-bundle -DCMAKE_CXX_FLAGS=-frtti -fexceptions -std=c++11 -DCMAKE_TOOLCHAIN_FILE=/home/username/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/username/Android/Sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_PLATFORM=android-27}
-- Configuring incomplete, errors occur  CMakeLists.txt
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

**Comment by daquexian** [comment]
Thanks for your issue!

Are you using [beta version of ndk](https://developer.android.com/ndk/downloads/index.html#beta-downloads)?

It looks like some paths on your PC are wrong. Please check out [this](https://github.com/googlesamples/android-ndk/issues/309) and [this](https://github.com/caffe2/caffe2/issues/732). And please let me know if you make some progress on it.

**Comment by bin913** [comment]
It works! Thanks for your instrucitons, In SDK manager, set updates->Automatically check  update for [beta channel] ,then update the sdk according recommendation. Reopen the project, and build the project successfully this time.

**Comment by daquexian** [comment]
@bin913 Great! Thanks for sharing your solution!

There are still many layers that I haven't supported :) But I'll try to keep updating. And any PRs are welcome.
