### ISSUE TITLE
Is this a command line tool? 

### ISSUE THREAD

**Issue by probonopd** [JDAI-CV/DNNLibrary#48]
`Usage: /run/firejail/appimage/.appimage-8418/AppRun onnx_model output_filename [table_file]` - is this a command line tool? Then it needs `Terminal=true` in the desktop file. Also it should do something useful when invoked without command line parameters.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1448

**Comment by daquexian** [comment]
Wow! Thanks for your effort on AppImage! It's cool! I will fix it soon.

**Comment by daquexian** [comment]
Just curious, how did you find this repo only several days after I used AppImage? :D

**Comment by daquexian** [comment]
Could you please clarify what "do something useful when invoked without command line parameters" means? Thanks.

**Comment by probonopd** [comment]
E.g, show a dialog box telling the user what to do. Something on the GUI that tells the user why the application is not working when being double-clicked.

> Just curious, how did you find this repo only several days after I used AppImage? :D

I 'm actively searching what people are doing with AppImage, in order to offer my help :-)

**Comment by daquexian** [comment]
@probonopd `Terminal=true` has been added in https://github.com/JDAI-CV/DNNLibrary/pull/50.

> E.g, show a dialog box telling the user what to do. Something on the GUI that tells the user why the application is not working when being double-clicked.

Does it need a GUI library like Qt or GTK? Is there any easy way to do it? Thanks!

**Comment by probonopd** [comment]
No, if it is a command line tool, then it does not need a GUI. Re-running the test now. Thanks.

**Comment by probonopd** [comment]
Well, please ping me once a new release containing the fix is on GitHub Releases. Maybe you'd like to do continuous builds? Check ouf https://github.com/probonopd/uploadtool for that.

**Comment by daquexian** [comment]
@probonopd Hi :) I have published new version containing this fix https://github.com/JDAI-CV/DNNLibrary/releases.

**Comment by probonopd** [comment]
Thank you very much.
