### ISSUE TITLE
Error:A problem occurred configuring project ':dnnlibrary'. > java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by nadeemb53** [JDAI-CV/DNNLibrary#7]
Getting the above error.
After adding implementation in dependencies, I am getting this error:
Error:(11, 1) A problem occurred evaluating root project 'DNNLibrary-master'.
> Could not find method implementation() for arguments [me.daquexian:dnnlibrary:0.1.7] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by daquexian** [comment]
Please use `compile 'me.daquexian:dnnlibrary:0.1.7'` instead of `implementation 'me.daquexian:dnnlibrary:0.1.7'` for gradle which version is lower than 3.0

Feel free to reopen this issue if it is not resolved.

**Comment by nadeemb53** [comment]
Gradle version is 3.0.1
I am getting this error with compile in dependencies:
Error:(12, 0) Could not find method compile() for arguments [me.daquexian:dnnlibrary:0.1.7] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
