### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by KristinHuangGH** [JDAI-CV/DNNLibrary#9]
I am studying your DNNLibrary.
In the Introduction of README.md, you mentioned that
"If you use the "raw" NNAPI, the code will increase dramatically. Setting up a LeNet needs 200+ lines. (For the 200+ lines LeNet you can check out the second commit of this repo)".

I want to study the LeNet using raw NNAPI. You said "you can check out the second commit of this repo", but I am not sure which commit you mean.
Do you mean the code is in Branch: LeNet?
Could you tell me which commit I can study?

Could you please help me?
Thank you very much!

**Comment by daquexian** [comment]
Hi :) It's c4ec0393aec9d22cce0c614e255b3d6b2e86f051. You could run `git reset --hard c4ec03` after you clone it. However the code contains a workaround for a bug in Android O MR1. You need remove the workaround like https://github.com/daquexian/DNNLibrary/commit/d2e0a31df5f87d26df478436b312adb0edb3aecf so that the code can run.

**Comment by daquexian** [comment]
If you [want to know](https://github.com/googlesamples/android-ndk/issues/531) the format of the weight, the weight purely consists of many 32bit floats. You might want to check out https://github.com/daquexian/dnntools, which contains the code produce the whole model file bin.

**Comment by daquexian** [comment]
@KristinHuangGH I'm closing this issue :) Feel free to reopen it if you need.

**Comment by KristinHuangGH** [comment]
Hello~
I read the LeNet using raw NNAPI(c4ec039).
How do you know the conv1InputIndexes[] = {0,7,8,16,15,15,17} for ANeuralNetworksModel_addOperation(ANEURALNETWORKS_CONV_2D)?
I mean that how do you know the input for conv1 are 0(input data), 7(conv1Weights), 8(conv1Biases), 16(valid padding), 15(int one), 15(int one) and 17(none activation)??
How do you know what kind of operand should be assigned for the specific Operation?
Where can I get this information?

**Comment by daquexian** [comment]
@KristinHuangGH It is documented in https://developer.android.com/ndk/reference/group/neural-networks

**Comment by KristinHuangGH** [comment]
I have checked OperationCode in the document, but I can't find the information.
For example, how do you know the input of MAX_POOL_2D are 1(conv1),16(valid padding),19(int two),19,19,19,17(none activation)?
Why input 19(int two) four times?
What does 19(int two) mean?

**Comment by daquexian** [comment]
@KristinHuangGH  I don't know what you mean. The parameters value are from LeNet caffemodel. And max_pool_2d is at https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a0f227a4d98ad5af31f7fd4d255d246ce
